version: '0.2'
services:
  vite:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '3000:3000'
    volumes:
    - '.:/app'
    command: /bin/sh -c "npm i && npm run dev"